# Generated by Django 4.1 on 2023-08-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Playlist Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Song Name'),
        ),
    ]
