# Generated by Django 4.1 on 2023-07-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collabartist_mainartist_delete_songartist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file',
            new_name='song_file',
        ),
        migrations.AddField(
            model_name='song',
            name='lyric_file',
            field=models.FileField(default='', upload_to='lyric/'),
        ),
    ]
