# Generated by Django 4.1 on 2023-08-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_artist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_artist',
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.profile'),
        ),
    ]
