# Generated by Django 4.1 on 2023-08-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_remove_mainartist_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
