# Generated by Django 4.1 on 2023-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='song',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyric_file',
            field=models.FileField(blank=True, null=True, upload_to='lyrics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
    ]
