# Generated by Django 4.1 on 2023-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_song_avatar_alter_song_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
    ]
