# Generated by Django 4.1 on 2023-09-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_playlist_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplayedplaylist',
            name='listens',
        ),
        migrations.RemoveField(
            model_name='userplayedsong',
            name='listens',
        ),
    ]
